export enum actionType {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAR_CART = "CLEAR_CART",
  UPDATE_QUANTITY = "UPDATE_QUANTITY",
  UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST",
  ADD_USER = "ADD_USER",
  REPLACE_CART = "REPLACE_CART",
  REPLACE_USER = "REPLACE_USER",
}
